define({
    "MINIFY"              : "Minimizar",
    "MINIFY_PROJECT"      : "Minimizar Proyecto",
    "MINIFY_ON_SAVE"      : "Minimizar al Guardar",
    "MINIFIER_PREFS"      : "Preferencias de Minimizar",
    "SAVE"                : "Guardar",
    "CANCEL"              : "Cancelar",
    "PREFS_TITLE"         : "Preferencias del Proyecto a minimizar",
    "PREFS_NOTE"          : "Estas preferencias se guardarán en la carpeta padre del proyecto, en el archivo <strong>.brackets.json</strong>.<br>ATENCIÓN: Todas les rutes personalizadas de guardar y de exclusión comienzan en la carpeta padre del proyecto.",
    "MINIFY_PROJECT_SAVE" : "Minimizar el Proyecto al Guardar \u2013 <strong>ATENCIÓN: 'Minimizar al Guardar' tiene que estar habilitado!</strong>",
    "MINIFY_JS"           : "Minimizar JavaScript durante la minimización del Proyecto",
    "MINIFY_CSS"          : "Minimizar CSS durante la minimización del Proyecto",
    "GENERATE_MAP"        : "Generar mapa de código fuente para los archivos '.js'",
    "KEEP_LICENSE"        : "Mantener la nota de licencia al inicio del archivo (si existeix)",
    "CUSTOM_JS_PATH"      : "Ruta personalitzada para los archivos Javascript minimizados (dejar en blanco para utilitzar la misma carpeta que el archivo original):",
    "CUSTOM_CSS_PATH"     : "Ruta personalitzada para los archivos CSS minimizados (dejar en blanco para utilitzar la misma carpeta que el archivo original):",
    "MINIFY_EXCLUDE"      : "Carpetas/Archivos a excluir durante el minimizado del Proyecto (cada uno en una nueva línea):",
    "PROJECT_MINIFIED"    : "Se ha minimizado el proyecto",
    "PROJECT_ERROR"       : "Algunos archivos no se han podido minimizar! Comprueba la consola",
    "FOLDER_ERROR"        : "Error al crear la carpeta de destino!",
    "MINIFIED"            : "Minimizado",
    "FILE_ERROR"          : "Error al guardar o al leer el archivo! Comprueba la consola",
    "GENERAL_ERROR"       : "Ha ocurrido un error! Comprueba la consola",
    "NOT_MINIFIABLE"      : "Este tipo de archivo no se puede minimizar",
    "ALREADY_MINIFIED"    : "El archivo ya està minimizado",
    "MINIFYING"           : "Minimizando\u2026",
    "MINIFYING_PROJECT"   : "Minimizando el proyecto\u2026",
    "NO_FILES"            : "No hay archivos a minimizar!",
});