define({
    "MINIFY"              : "Minify",
    "MINIFY_PROJECT"      : "Minify Project",
    "MINIFY_ON_SAVE"      : "Minify on Save",
    "MINIFIER_PREFS"      : "Minifier Preferences",
    "SAVE"                : "Save",
    "CANCEL"              : "Cancel",
    "PREFS_TITLE"         : "Minifier Project Preferences",
    "PREFS_NOTE"          : "These preferences will be saved to the current project's root folder in the <strong>.brackets.json</strong> file.<br>NOTE: All custom save and exclude paths begin at project root folder.",
    "MINIFY_PROJECT_SAVE" : "Minify Project on Save \u2013 <strong>NOTE: 'Minify on Save' must be checked!</strong>",
    "MINIFY_JS"           : "Minify JavaScript during Project Minification",
    "MINIFY_CSS"          : "Minify CSS during Project Minification",
    "CUSTOM_JS_PATH"      : "Custom Path for Minified JavaScript (leave blank for same folder as original file):",
    "CUSTOM_CSS_PATH"     : "Custom Path for Minified CSS (leave blank for same folder as original file):",
    "MINIFY_EXCLUDE"      : "Directories/Files to Exclude from Project Minification (each on seperate line):",
    "UGLIFYJS_SETTINGS"   : "UglifyJS2 Settings (only apply to current project)",
    "MANGLE_JS"           : "Mangle JavaScript",
    "COMPRESS_JS"         : "Compress JavaScript",
    "PROJECT_MINIFIED"    : "Project Minified",
    "PROJECT_ERROR"       : "Some files couldn't be minified! Check console",
    "FOLDER_ERROR"        : "Error creating target folder!",
    "MINIFIED"            : "Minified",
    "FILE_ERROR"          : "Error saving or reading file! Check console",
    "GENERAL_ERROR"       : "Error occured! Check console",
    "NOT_MINIFIABLE"      : "Filetype not minifiable",
    "ALREADY_MINIFIED"    : "File already minified",
    "MINIFYING"           : "Minifying\u2026",
    "MINIFYING_PROJECT"   : "Minifying project\u2026",
    "NO_FILES"            : "No files to minify!",
});