define({
    "MINIFY"              : "Pienennä",
    "MINIFY_PROJECT"      : "Pienennä projekti",
    "MINIFY_ON_SAVE"      : "Pienennä tallennettaessa",
    "MINIFIER_PREFS"      : "Pienentimen asetukset",
    "SAVE"                : "Tallenna",
    "CANCEL"              : "Peruuta",
    "PREFS_TITLE"         : "Pienentimen projektiasetukset",
    "PREFS_NOTE"          : "Nämä asetukset tallennetaan nykyisen projektin juurikansion tiedostoon <strong>.brackets.json</strong>.<br>HUOM.: kaikki mukautetut tallennus- ja ohituspolut alkavat projektin juurikansiosta.",
    "MINIFY_PROJECT_SAVE" : "Pienennä projekti tallennettaessa \u2013 <strong>HUOM.: valinnan ”Pienennä tallennettaessa” täytyy olla valittuna!</strong>",
    "MINIFY_JS"           : "Pienennä JavaScript",
    "MINIFY_CSS"          : "Pienennä CSS",
    "GENERATE_MAP"        : "Luo lähdekartat .js-tiedostoille",
    "KEEP_LICENSE"        : "Säilytä alkuosan lisenssi-ilmoitus (jos sellainen on)",
    "CUSTOM_JS_PATH"      : "Mukautettu pienennetyn JavaScriptin polku:",
    "CUSTOM_CSS_PATH"     : "Mukautettu pienennetyn CSS:n polku:",
    "MINIFY_EXCLUDE"      : "Ohitettavat hakemistot tai tiedostot (kukin omalle rivilleen):",
    "PROJECT_MINIFIED"    : "Projekti pienennetty",
    "PROJECT_ERROR"       : "Joitakin tiedostoja ei voitu pienentää! Tarkista konsoli",
    "FOLDER_ERROR"        : "Virhe luotaessa kohdekansiota!",
    "MINIFIED"            : "Pienennetty",
    "FILE_ERROR"          : "Virhe tallennettaessa tai luettaessa tiedostoa! Tarkista konsoli",
    "GENERAL_ERROR"       : "Tapahtui virhe! Tarkista konsoli",
    "NOT_MINIFIABLE"      : "Tiedostotyyppi ei ole pienennettävä",
    "ALREADY_MINIFIED"    : "Tiedosto on jo pienennetty",
    "MINIFYING"           : "Pienennetään\u2026",
    "MINIFYING_PROJECT"   : "Pienennetään projektia\u2026",
    "NO_FILES"            : "Ei pienennettäviä tiedostoja!",
});
