define({
    "MINIFY"              : "Minify",
    "MINIFY_PROJECT"      : "Progetto Minify",
    "MINIFY_ON_SAVE"      : "Minify al salvataggio",
    "MINIFIER_PREFS"      : "Minifier Preferenze",
    "SAVE"                : "Salva",
    "CANCEL"              : "Cancella",
    "PREFS_TITLE"         : "Preferenze Progetto Minifier",
    "PREFS_NOTE"          : "Queste prefenze saranno salvate nel progetto attuale nella cartella principale in <strong>.brackets.json</strong> file.<br>NOTA: Tutti i salvataggi escludeso i percorsi personalizzati iniziano alle cartella principale del progetto.",
    "MINIFY_PROJECT_SAVE" : "Minify Project al Salvataggio \u2013 <strong>NOTA: 'Minify al Savataggio' deve essere selezionato!</strong>",
    "MINIFY_JS"           : "Minify JavaScript",
    "MINIFY_CSS"          : "Minify CSS",
    "CUSTOM_JS_PATH"      : "Personalizza percorso Minified JavaScript:",
    "CUSTOM_CSS_PATH"     : "Personalizza percorso Minified CSS:",
    "GENERATE_MAP"        : "Generate source maps for .js files",
    "KEEP_LICENSE"        : "Keep license notice at the beginning (if exists)",
    "MINIFY_EXCLUDE"      : "Cartelle/File esclusi (ciascuno su una riga separata):",
    "UGLIFYJS_SETTINGS"   : "Impostazioni UglifyJS2 (solo applicato al progetto attuale)",
    "MANGLE_JS"           : "Mangle JavaScript",
    "COMPRESS_JS"         : "Compress JavaScript",
    "PROJECT_MINIFIED"    : "Progetto Minified",
    "PROJECT_ERROR"       : "Qualche file non può essere minimizzato! Controlla console",
    "FOLDER_ERROR"        : "Errore nella creazione della cartella di destinazione!",
    "MINIFIED"            : "Minimizza",
    "FILE_ERROR"          : "Errore al salvataggio oppure alla lettura del file! Controlla console",
    "GENERAL_ERROR"       : "Errore! Controllare console",
    "NOT_MINIFIABLE"      : "Tipo di file non supportato",
    "ALREADY_MINIFIED"    : "File già minimizzato",
    "MINIFYING"           : "Minizzazione in corso\u2026",
    "MINIFYING_PROJECT"   : "Minimizzazione progetto in corso\u2026",
    "NO_FILES"            : "Nessun file da Minimizzare!",
});