define({
    "MINIFY"              : "Minimitzar",
    "MINIFY_PROJECT"      : "Minimitzar Projecte",
    "MINIFY_ON_SAVE"      : "Minimitzar al Guardar",
    "MINIFIER_PREFS"      : "Preferències de Minimitzar",
    "SAVE"                : "Guardar",
    "CANCEL"              : "Cancelar",
    "PREFS_TITLE"         : "Preferències de Projecte per Minimitzar",
    "PREFS_NOTE"          : "Aquestes preferències seran guardades a la carpeta pare del projecte, a l'arxiu <strong>.brackets.json</strong>.<br>ATENCIÓ: Totes les rutes personalitzades de guardar i excloure comencen a la carpeta pare del projecte.",
    "MINIFY_PROJECT_SAVE" : "Minimitzar el Projecte al Guardar \u2013 <strong>ATENCIÓ: 'Minimitzar al Guardar' ha d'estar habilitat!</strong>",
    "MINIFY_JS"           : "Minimitzar JavaScript durant el minimitzat del Projecte",
    "MINIFY_CSS"          : "Minimitzar CSS durant el minimitzat del Projecte",
    "GENERATE_MAP"        : "Generar mapa de codi font per als arxius '.js'",
    "KEEP_LICENSE"        : "Mantenir la nota de llicència a l'inici de l'arxiu (si existeix)",
    "CUSTOM_JS_PATH"      : "Ruta personalitzada per als arxius Javascript minimitzats (deixar-ho en blanc per utilitzar la mateixa carpeta que l'arxiu original):",
    "CUSTOM_CSS_PATH"     : "Ruta personalitzada per als arxius CSS minimitzats (deixar-ho en blanc per utilitzar la mateixa carpeta que l'arxiu original):",
    "MINIFY_EXCLUDE"      : "Carpetes/Arxius a excloure durant el minimitzat del Projecte (cada un en una nova línea):",
    "PROJECT_MINIFIED"    : "S'ha minimitzat el projecte",
    "PROJECT_ERROR"       : "Alguns arxius no s'han pogut minimitzar! Comprova la consola",
    "FOLDER_ERROR"        : "Error al crear la carpeta de destí!",
    "MINIFIED"            : "Minimitzat",
    "FILE_ERROR"          : "Error al guardar o al llegir l'arxiu! Comprova la consola",
    "GENERAL_ERROR"       : "Ha ocorregut un error! Comprova la consola",
    "NOT_MINIFIABLE"      : "Aquest tipus d'arxiu no es pot minimitzar",
    "ALREADY_MINIFIED"    : "L'arxiu ja està minimitzat",
    "MINIFYING"           : "Minimitzant\u2026",
    "MINIFYING_PROJECT"   : "Minimitzant el projecte\u2026",
    "NO_FILES"            : "No hi ha arxius a minimitzar!",
});