define({
    "MINIFY"              : "Minimieren",
    "MINIFY_PROJECT"      : "Projekt minimieren",
    "MINIFY_ON_SAVE"      : "Minimieren beim Speichern",
    "SAVE"                : "Speichern",
    "CANCEL"              : "Abbrechen",
    "PREFS_NOTE"          : "Diese Einstellungen werden im Root-Verzeichnis des aktuellen Projekts in die <strong>.brackets.json</strong> Datei gespeichert.<br>HINWEIS: Alle angepassten Speicher- und Ausschlusspfade beginnen im Root-Verzeichnis des Projekts.",
    "MINIFY_PROJECT_SAVE" : "Minimiere Projekt beim Speichern \u2013 <strong>HINWEIS: 'Minimieren beim Speichern' muss aktiviert sein!</strong>",
    "MINIFY_JS"           : "Minimiere JavaScript beim Minimieren des Projekts",
    "MINIFY_CSS"          : "Minimiere CSS beim Minimieren des Projekts",
    "GENERATE_MAP"        : "Generiere Source Maps für .js Dateien",
    "KEEP_LICENSE"        : "Behalte Lizenz-Hinweis am Anfang (wenn vorhanden)",
    "CUSTOM_JS_PATH"      : "Angepasster Pfad für minimiertes JavaScript (frei lassen für selben Ordner wie Originaldatei):",
    "CUSTOM_CSS_PATH"     : "Angepasster Pfad für minimiertes CSS (frei lassen für selben Ordner wie Originaldatei):",
    "MINIFY_EXCLUDE"      : "Ordner/Dateien die von der Projekt-Minimierung ausgeschlossen werden sollen (jeweils in einer seperaten Zeile):",
    "PROJECT_MINIFIED"    : "Projekt minimiert",
    "PROJECT_ERROR"       : "Einige Dateien konnten nicht minimiert werden. Prüfe die Konsole!",
    "FOLDER_ERROR"        : "Fehler beim Erstellen des Zielordners!",
    "MINIFIED"            : "Minimiert",
    "FILE_ERROR"          : "Fehler beim Speichern oder Lesen der Datei. Prüfe die Konsole!",
    "GENERAL_ERROR"       : "Es ist ein Fehler aufgetreten. Prüfe die Konsole!",
    "NOT_MINIFIABLE"      : "Dateityp nicht minimierbar",
    "ALREADY_MINIFIED"    : "Datei wurde bereits minimiert",
    "MINIFYING"           : "Minimiere\u2026",
    "MINIFYING_PROJECT"   : "Minimiere Projekt\u2026",
    "NO_FILES"            : "Keine Dateien zum Minimieren!",
});
